config/routes.rb
FirstApp::Application.routes.draw do

root to: 'home#mainpage'

match '/bio', to: 'home#bio'
match '/balloonacy', to: 'home#balloonacy'
match '/wave', to: 'home#wave'
match '/dj_straus', to: 'home#dj_straus'
match '/sf_funk_truck', to: 'home#sf_funk_truck'
match '/examer_slammer', to: 'home#examer_slammer'
match '/before_i_graduate', to: 'home#before_i_graduate'
match '/awesome_foundation', to: 'home#awesome_foundation'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def view
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def view
	end


	def mainpage
	end

	def bio
	end

	def balloonacy
	end

	def awesome_foundation
	end

	def wave
	end

	def examer_slammer
	end
	
	def sf_funk_truck
	end
	
	def dj_straus
	end
	
	def awesome_foundation
	end

	def before_i_graduate
	end
	
	


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/awesome_foundation.html.erb
<%= image_tag('AF-logo.png') %>
<br></br>
<div class='description-text'>
The <%= link_to 'Awesome Foundation', 'http://awesomefoundation.org' %> is an ever-growing, worldwide network of people devoted to forwarding the interest of awesomeness in the universe. Created in the long hot summer days of 2009 in Boston, the Foundation distributes a series of monthly $1,000 grants to projects and their creators. The money is pooled together from the coffers of ten or so self-organizing “micro-trustees” and given upfront in cash, check, or gold doubloons. The 47+ chapters around the world are autonomous and organized by the trustees around geographic areas or topics of interest.
<br></br>
The Foundation provides these grants with no strings attached and claims no ownership over the projects it supports. It is, in the words of one trustee, a micro-genius grant for flashes of micro-brilliance.
<br></br>

<u><b>Role:</b></u>  Trustee, San Francisco Chapter

<br></br>
<p class='description-text'><u>Past San Francisco grants include:</u></p>
<ul>
<li>A Timelapse History of the Sky</li>
<li>Bathtub Street Gondola</li>
<li>Lunar Topography Laser Carvings</li>
</ul>

</div>

app/views/home/balloonacy.html.erb
<iframe width="640" height="360" width = 'auto' src="http://www.youtube.com/embed/bZFJgNjDPKQ" frameborder="0" allowfullscreen></iframe>

<div class='description-text'>
<br></br>
 Balloonacy! was the World's First Ever Interactive Balloon Immersion.
<br></br>
On May 12-13, 2012 over 2,000 San Franciscans came out and rediscovered the playful side of life as they waded their way through a pitch black sea of thousands of light-emitting, motion-sensitive balloons. It was part dance-party, part existential crisis, and ALL FUN!
<br></br>
The project was graciously funded by <%= link_to 'The Awesome Foundation', 'http://awesomefoundation.org' %> and held in the <%= link_to 'Million Fishes', 'http://millionfishes.com' %> Gallery

</div>

app/views/home/before_i_graduate.html.erb
<%= image_tag('before i graduate.jpeg') %>
<br></br>
<div class='description-text'>
"Before I Graduate..." was conceived in my waning days of senior year at college, and inspired by Candy Chang's <%= link_to "Before I Die...", 'http://beforeidie.cc'%>  wall in New Orleans. For overworked students, its far too easy to fall into a rut and forget about how finite their time on campus is. The project was meant to counteract this by provided the campus with a fun, playful, community bucketlist.
<br></br>

I set up a 23-foot-long chalkboard in the heart of campus with the repeating words “I want to,” followed by a blank space and colorful chalk nearby. Within hours students had completely overwhelmed the board with their hopes and dreams for the future. Responses ranged from the more playful "Go streaking" and "Kiss a crew boy" to the more personal "Make a difference" and "Not be ashamed of myself"

<br></br>
</p><b><u>Press:</b></u></p>
<p class='description-text'><%= link_to 'The Harvard Crimson', 'http://www.thecrimson.com/article/2011/4/19/things-before-seniors-want/' %></p>

</div>

app/views/home/bio.html.erb
	<div id='bio_pic'>
	<p><%= image_tag('george clones.jpg') %></p>
	</div>
	

<div class='description-text'>
<p class='description-text'>I'm happiest when I'm making awesome things happen. </p>
<p class='description-text'>I take an adventure-centric approach to life and relish poking the world around me.</p>
<p class='description-text'></p>
<br></br>
<p class='description-text'>Born and raised in New York City, studied sociology at Harvard, and currently exploring San Francisco.</p>
<p class='description-text'> My projects strive to create unique and inspiring experiences that positively reshape people's interactions with the world.</p>
<p class='description-text'> They tend to explore themes of community, play, and how of how to best inject doses of Awesomeness into daily life.</p>
<br> </br>
<p class='description-text'>Daytime --> Leading user research at <%= link_to 'CouchSurfing.org', 'http://www.couchsurfing.org' %></p> 
<p class='description-text'>Othertime --> Scheming up one whimsical project after another</p> 
<br> </br>

I'd probably love to meet you.
<p class='description-text'>Lets experiment. Together!</p>

<br></br>

George.Zisiadis@gmail.com
</div>

app/views/home/dj_straus.html.erb
<%= image_tag('DjStraus-wText.jpg') %>
<br></br>
<iframe width="85%" height="166" scrolling="no" frameborder="no" src="http://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F231717&amp;auto_play=false&amp;show_artwork=false&amp;color=ff9c00"></iframe>

<div class='description-text'>
DJ Straus was born out of my desire to deliver a college musical experience that extended beyond hopelessly replayed top 40 songs. From Guns n Roses to Lady Gaga, The Beatles to LMFAO, my mashed up mixing cut across all genres, styles, and expectations.
<br></br>

Within a semester, Straus had played at a dozen major campus events and the monthly ten-minute mixes had garnered over 6,700 plays and 800+ downloads. The brand had by then become a well-known force for good in the campus music scene. 


<br></br>
</p><b><u>Press:</b></u></p>
<p class='description-text'><%= link_to 'The Harvard Crimson', 'http://www.thecrimson.com/article/2010/3/2/the-dutiful-dj/' %></p>

</div>

app/views/home/examer_slammer.html.erb
<%= image_tag('Examer_Slammer.jpeg') %>
<br></br>
<div class='description-text'>
	Developed in the midst of a grueling college finals period, The Exammer Slammer arose out of the frustration of finishing one exam only to begin studying for the other. Where was the intermittent celebration?!
<br></br>

	Exasperated, I threw together a quill, a stack of yellow paper, and an 8-foot decorated chicken wire tube in my house dining hall with the following instructions:
<br></br>
<i>
<p class='description-text'>1) Take the quill and inscribe the name of the finished course on the yellow paper.</p>
<p class='description-text'>2) Write a heartfelt message to your course and sign it with your name.</p>
<p class='description-text'>3) CRUMPLE IT UP!</p>
<p class='description-text'>4) Climb to the top of the Adams House Chair of Cheer, and...</p>
5) SLAM! it in as a sign of your triumph over adversity and your success in completing your course.</i>
<br></br>
	With over 1,000 submissions in one week, The Exammer Slammer provided students some much needed catharsis by enabling them to visualize and collectively celebrate their triumph over the status quo of misery. 
<br></br>
</p><b><u>Press:</b></u></p>
<p class='description-text'><%= link_to 'The Harvard Crimson', 'http://www.thecrimson.com/article/2010/12/21/adams-zisiadis-paper-course/' %></p>

</div>

app/views/home/mainpage.html.erb
<div class='container-fluid'>
    
    	<div class = 'project-thumb'>
      	<%= link_to image_tag('balloonacy_color.png'), balloonacy_path%>
		<div id = 'text-balloon' class='text'> Balloonacy! </div>
		</div>

		<div class = 'project-thumb'>
		<%= link_to image_tag('funk truck screengrab.png'), sf_funk_truck_path %>
		<div class = 'text'> SF Funk Truck </div>
		</div>

		<div class = 'project-thumb'>
		<%= link_to image_tag('WAVE.jpg'), wave_path %>
		<div class = 'text'>WAVE </div>
		</div>

		<div class = 'project-thumb'>	
		<%= link_to image_tag('awesomefoundation.png'), awesome_foundation_path %>
		<div class = 'text'> <p class = 'text'>The Awesome</p> <p class = 'text'>Foundation</p> </div>
		</div>

		<div class = 'project-thumb'>	
		<%= link_to image_tag('Examer_Slammer.jpeg'), examer_slammer_path %>
		<div class = 'text'><p class = 'text'>The Exammer</p> <p class = 'text'> Slammer </p> </div>
		</div>

		<div class = 'project-thumb'>	
		<%= link_to image_tag('before i graduate.jpeg'), before_i_graduate_path %>
		<div class = 'text'>Before I Graduate... </div>
		</div>

		<div class = 'project-thumb'>	
		<%= link_to image_tag('DjStraus-wText.jpg
		'), dj_straus_path %>
		<div class = 'text'> DJ Straus </div>
		</div>
   
</div>

app/views/home/sf_funk_truck.html.erb
<iframe src="http://player.vimeo.com/video/39464915" width="640" height="360" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
<div class='description-text'>

	Everyone loves music. So why not more of it?

	<p class='description-text'>On a sunny Saturday afternoon in March 2012 the SF Funk Truck made its debut tour across the city.</p> <p class='description-text'>Needless to say, there was dancing, cheering, and just an all around good time had by all. </p>
<br></br>
	Hardly anyone could bear to walk the streets that day without revealing a smile. 

</div>

app/views/home/wave.html.erb
<div class='page-pic'>
<%= image_tag('WAVE.jpg') %>
</div>
<br></br>

<div class='description-text'>
	Created by artist <%= link_to 'Charles Gadeken', 'http://charlesgadeken.com' %> and premiered at the 2012 Coachella Valley Music and Arts Festival,
	WAVE is the world’s tallest wave generator. It's constructed from four 30-foot towers that dance on the horizon, illuminated from within by full color LEDs and by fire at the apex. The slow moving, high amplitude transverse waves provide a physical example for the visualization of this complex and changing phenomena. WAVE thus takes architecture and science to the edge of abstraction.
<br></br>
	The overall effect of the work is massive, surreal, intimidating, hypnotic and simply stunning.
<br></br>
<u><b>Role:</b></u>  Construction and Maintainance Crew

</div>

app/views/layouts/_nav.html.erb
    <div  id = "nav">
    	<h1 id= 'name' class = 'hover-red'><%= link_to 'George Zisiadis', root_path, id: 'name' %></h1>

		<div id = 'navbar'>
		<p class = 'navtext'><%= link_to 'Who?', bio_path, class: 'navtext' %></p>
		<p>  </p>
		<div id = 'line'></div>
			<p class = 'project-text'><%= link_to 'Balloonacy!', balloonacy_path, class: 'project-text'  %></p>
			<p class = 'project-text'><%= link_to 'SF Funk Truck', sf_funk_truck_path, class: 'project-text'  %></p>
			<p class = 'project-text'><%= link_to 'Exammer Slammer', examer_slammer_path, class: 'project-text'  %></p>
			<p class = 'project-text'><%= link_to 'Before I Graduate', before_i_graduate_path, class: 'project-text'  %></p>
			<p class = 'project-text'><%= link_to 'WAVE', wave_path, class: 'project-text' %></p>
			<p class = 'project-text'><%= link_to 'DJ Straus', dj_straus_path, class: 'project-text'  %></p>
			<p class = 'project-text'><%= link_to 'Awesome Foundation', awesome_foundation_path, class: 'project-text'  %></p>

			
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>George Zisiadis</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33674966-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>

<%= render 'layouts/nav' %>

<div  class='body'>
<%= yield %>
</div>

</body>


</html>